# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d18d9273b782a88958b2f358afcbd31"
name = "wishlist-app"
handle = "wishlist-app-162"
application_url = "https://inherited-donna-jr-apparent.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "evolution-app-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://inherited-donna-jr-apparent.trycloudflare.com/auth/callback",
  "https://inherited-donna-jr-apparent.trycloudflare.com/auth/shopify/callback",
  "https://inherited-donna-jr-apparent.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
